services:
  _defaults:
    autowire: true
    autoconfigure: true

  Pushword\AdvancedMainImage\:
    resource: "../*"
    exclude: "../{DependencyInjection,Entity,Migrations,Tests,config,Kernel.php}"
